-- MoneyFollows — full database setup. Paste into Supabase → SQL Editor → Run.
-- Generated by `npm run db:bundle`. Safe to run once on a fresh project.

create schema if not exists app_private;
revoke all on schema app_private from public;
create table if not exists app_private.migrations (name text primary key, applied_at timestamptz not null default now());

-- ════════════════════════════════════════ 0001_schema.sql
-- MoneyFollows — core schema
-- Every user-owned table has user_id → auth.users. Child rows reference their
-- parent through composite (id, user_id) foreign keys, so a row can never point
-- at another user's category/subcategory/transaction, even before RLS applies.

-- ─────────────────────────────────────────────────────────────── enums
create type public.transaction_type as enum ('EXPENSE', 'INCOME', 'INVESTMENT');
create type public.recurrence_frequency as enum ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY');
create type public.investment_type as enum ('SIP', 'MUTUAL_FUND', 'STOCKS', 'PPF', 'FD', 'OTHER');
create type public.investment_frequency as enum ('ONE_TIME', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY');
create type public.custom_field_type as enum ('TEXT', 'NUMBER', 'DROPDOWN', 'BOOLEAN', 'DATE');

-- ─────────────────────────────────────────────────────────────── helpers
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ─────────────────────────────────────────────────────────────── profiles
create table public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  full_name   text check (char_length(full_name) <= 80),
  currency    char(3) not null default 'INR' check (currency ~ '^[A-Z]{3}$'),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────── categories
create table public.categories (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  type         public.transaction_type not null,
  name         text not null check (char_length(btrim(name)) between 1 and 40),
  icon         text not null default 'other' check (char_length(icon) <= 40),
  color        text not null default 'slate' check (char_length(color) <= 20),
  sort_order   integer not null default 0,
  is_system    boolean not null default false,
  archived_at  timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (id, user_id),
  unique (id, user_id, type)
);
create unique index categories_user_type_name_key on public.categories (user_id, type, lower(name));
create index categories_user_idx on public.categories (user_id, type, sort_order);

create table public.subcategories (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  category_id  uuid not null,
  name         text not null check (char_length(btrim(name)) between 1 and 40),
  sort_order   integer not null default 0,
  archived_at  timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (id, user_id),
  unique (id, user_id, category_id),
  foreign key (category_id, user_id) references public.categories (id, user_id) on delete cascade
);
create unique index subcategories_category_name_key on public.subcategories (category_id, lower(name));
create index subcategories_user_idx on public.subcategories (user_id);

-- ─────────────────────────────────────────────────────────────── investments
create table public.investments (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name        text not null check (char_length(btrim(name)) between 1 and 80),
  type        public.investment_type not null,
  amount      numeric(14, 2) not null check (amount > 0),
  frequency   public.investment_frequency not null default 'MONTHLY',
  start_date  date not null default current_date,
  end_date    date,
  notes       text check (char_length(notes) <= 1000),
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (id, user_id),
  check (end_date is null or end_date >= start_date)
);
create index investments_user_idx on public.investments (user_id, active);

-- ─────────────────────────────────────────────────────────────── recurring
create table public.recurring_transactions (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null default auth.uid() references auth.users (id) on delete cascade,
  type            public.transaction_type not null,
  amount          numeric(14, 2) not null check (amount > 0),
  category_id     uuid not null,
  subcategory_id  uuid,
  description     text check (char_length(description) <= 200),
  frequency       public.recurrence_frequency not null,
  start_date      date not null,
  end_date        date,
  next_run_date   date not null,
  is_purchase     boolean not null default false,
  investment_id   uuid,
  active          boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (id, user_id),
  check (end_date is null or end_date >= start_date),
  foreign key (category_id, user_id, type) references public.categories (id, user_id, type),
  foreign key (subcategory_id, user_id, category_id) references public.subcategories (id, user_id, category_id),
  foreign key (investment_id, user_id) references public.investments (id, user_id) on delete set null (investment_id)
);
create index recurring_due_idx on public.recurring_transactions (user_id, next_run_date) where active;

-- ─────────────────────────────────────────────────────────────── transactions
create table public.transactions (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null default auth.uid() references auth.users (id) on delete cascade,
  type              public.transaction_type not null,
  amount            numeric(14, 2) not null check (amount > 0 and amount < 1000000000000),
  category_id       uuid not null,
  subcategory_id    uuid,
  transaction_date  date not null default current_date,
  description       text check (char_length(description) <= 200),
  notes             text check (char_length(notes) <= 1000),
  custom_metadata   jsonb not null default '{}'::jsonb check (jsonb_typeof(custom_metadata) = 'object'),
  is_purchase       boolean not null default false,
  recurring_id      uuid,
  investment_id     uuid,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (id, user_id),
  -- category must belong to the same user AND match the transaction type
  foreign key (category_id, user_id, type) references public.categories (id, user_id, type),
  -- subcategory must belong to the same user AND to the chosen category
  foreign key (subcategory_id, user_id, category_id) references public.subcategories (id, user_id, category_id),
  foreign key (recurring_id, user_id) references public.recurring_transactions (id, user_id) on delete set null (recurring_id),
  foreign key (investment_id, user_id) references public.investments (id, user_id) on delete set null (investment_id)
);
create index transactions_user_date_idx on public.transactions (user_id, transaction_date desc, created_at desc);
create index transactions_user_type_date_idx on public.transactions (user_id, type, transaction_date);
create index transactions_category_idx on public.transactions (category_id, transaction_date);
create index transactions_subcategory_idx on public.transactions (subcategory_id) where subcategory_id is not null;
create index transactions_purchase_idx on public.transactions (user_id, transaction_date) where is_purchase;
create index transactions_recurring_idx on public.transactions (recurring_id) where recurring_id is not null;
create index transactions_investment_idx on public.transactions (investment_id) where investment_id is not null;

-- ─────────────────────────────────────────────────────────────── custom fields
create table public.custom_field_definitions (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name        text not null check (char_length(btrim(name)) between 1 and 40),
  field_type  public.custom_field_type not null,
  -- DROPDOWN choices: ["UPI", "Card", "Cash"]
  options     jsonb not null default '[]'::jsonb check (jsonb_typeof(options) = 'array'),
  sort_order  integer not null default 0,
  archived_at timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (id, user_id)
);
create unique index custom_fields_user_name_key on public.custom_field_definitions (user_id, lower(name));

create table public.transaction_custom_fields (
  transaction_id  uuid not null,
  field_id        uuid not null,
  user_id         uuid not null default auth.uid() references auth.users (id) on delete cascade,
  value           jsonb not null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  primary key (transaction_id, field_id),
  foreign key (transaction_id, user_id) references public.transactions (id, user_id) on delete cascade,
  foreign key (field_id, user_id) references public.custom_field_definitions (id, user_id) on delete cascade
);
create index transaction_custom_fields_field_idx on public.transaction_custom_fields (field_id);
create index transaction_custom_fields_user_idx on public.transaction_custom_fields (user_id);

-- ─────────────────────────────────────────────────────────────── budgets
create table public.budgets (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  category_id  uuid not null,
  month        date not null check (extract(day from month) = 1),
  amount       numeric(14, 2) not null check (amount > 0),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (user_id, category_id, month),
  foreign key (category_id, user_id) references public.categories (id, user_id) on delete cascade
);
create index budgets_category_idx on public.budgets (category_id);

-- ─────────────────────────────────────────────────────────────── goals
create table public.financial_goals (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name            text not null check (char_length(btrim(name)) between 1 and 60),
  target_amount   numeric(14, 2) not null check (target_amount > 0),
  current_amount  numeric(14, 2) not null default 0 check (current_amount >= 0),
  target_date     date,
  icon            text not null default 'growth',
  color           text not null default 'green',
  achieved_at     timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index financial_goals_user_idx on public.financial_goals (user_id);

-- ─────────────────────────────────────────────────────────────── monthly plans
create table public.monthly_plans (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null default auth.uid() references auth.users (id) on delete cascade,
  month           date not null check (extract(day from month) = 1),
  monthly_income  numeric(14, 2) not null default 0 check (monthly_income >= 0),
  -- { rent, emi, family_support, investments, goals }
  inputs          jsonb not null default '{}'::jsonb check (jsonb_typeof(inputs) = 'object'),
  -- { needs: 50, lifestyle: 15, family: 10, investments: 15, savings: 5, flexible: 5 }
  allocations     jsonb not null default '{}'::jsonb check (jsonb_typeof(allocations) = 'object'),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (user_id, month)
);

-- ─────────────────────────────────────────────────────────────── updated_at triggers
do $$
declare t text;
begin
  foreach t in array array[
    'profiles', 'categories', 'subcategories', 'investments', 'recurring_transactions',
    'transactions', 'custom_field_definitions', 'transaction_custom_fields', 'budgets',
    'financial_goals', 'monthly_plans'
  ] loop
    execute format(
      'create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()', t
    );
  end loop;
end $$;

insert into app_private.migrations (name) values ('0001_schema.sql') on conflict do nothing;

-- ════════════════════════════════════════ 0002_rls.sql
-- MoneyFollows — Row Level Security
-- A signed-in user can only see and change their own rows. Anonymous users get nothing.
-- `(select auth.uid())` is evaluated once per statement instead of once per row.

alter table public.profiles                  enable row level security;
alter table public.categories                enable row level security;
alter table public.subcategories             enable row level security;
alter table public.investments               enable row level security;
alter table public.recurring_transactions    enable row level security;
alter table public.transactions              enable row level security;
alter table public.custom_field_definitions  enable row level security;
alter table public.transaction_custom_fields enable row level security;
alter table public.budgets                   enable row level security;
alter table public.financial_goals           enable row level security;
alter table public.monthly_plans             enable row level security;

-- profiles: keyed by id (= auth.users.id). Rows are created by the signup trigger.
create policy "profiles_select_own" on public.profiles
  for select to authenticated using ((select auth.uid()) = id);
create policy "profiles_update_own" on public.profiles
  for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

-- Every other table: full CRUD on own rows only.
do $$
declare t text;
begin
  foreach t in array array[
    'categories', 'subcategories', 'investments', 'recurring_transactions', 'transactions',
    'custom_field_definitions', 'transaction_custom_fields', 'budgets', 'financial_goals',
    'monthly_plans'
  ] loop
    execute format(
      'create policy %I on public.%I for select to authenticated using ((select auth.uid()) = user_id)',
      t || '_select_own', t);
    execute format(
      'create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)',
      t || '_insert_own', t);
    execute format(
      'create policy %I on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)',
      t || '_update_own', t);
    execute format(
      'create policy %I on public.%I for delete to authenticated using ((select auth.uid()) = user_id)',
      t || '_delete_own', t);
  end loop;
end $$;

-- Defence in depth: anon has no business with app tables at all.
revoke all on all tables in schema public from anon;

insert into app_private.migrations (name) values ('0002_rls.sql') on conflict do nothing;

-- ════════════════════════════════════════ 0003_new_user_seed.sql
-- MoneyFollows — per-user defaults
-- On signup: create the profile and seed default categories/subcategories.
-- Keep in sync with lib/constants/categories.ts.

create or replace function public.seed_default_categories(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  cat record;
  new_id uuid;
  sub text;
  i integer;
begin
  for cat in
    select * from (values
      -- type, name, icon, color, sort, subcategories
      ('EXPENSE', 'Food',          'food',          'orange', 1,  array['Lunch','Dinner','Breakfast','Milk','Snacks','Restaurant','Other']),
      ('EXPENSE', 'Transport',     'transport',     'sky',    2,  array['Petrol','Bike Service','Car Service','Cab','Bus','Parking','Other']),
      ('EXPENSE', 'Housing',       'housing',       'indigo', 3,  array['Rent','Maintenance','Other']),
      ('EXPENSE', 'Bills',         'bills',         'slate',  4,  array['Electricity','Internet','Mobile','Insurance','Other']),
      ('EXPENSE', 'Family',        'family',        'coral',  5,  array['Parents','Brother','Sister','Family','Other']),
      ('EXPENSE', 'Lifestyle',     'lifestyle',     'pink',   6,  array['Gym','Skincare','Haircut','Clothing','Accessories','Other']),
      ('EXPENSE', 'Shopping',      'shopping',      'violet', 7,  array['Electronics','Watch','Shoes','Accessories','Other']),
      ('EXPENSE', 'Entertainment', 'entertainment', 'amber',  8,  array['Movie','OTT','Games','Events','Other']),
      ('EXPENSE', 'Health',        'health',        'green',  9,  array['Medicine','Doctor','Other']),
      ('EXPENSE', 'Education',     'education',     'blue',   10, array['Course','Books','Certification','Other']),
      ('EXPENSE', 'Other',         'other',         'slate',  11, array[]::text[]),
      ('INCOME',  'Salary',        'salary',        'green',  1,  array[]::text[]),
      ('INCOME',  'Freelance',     'freelance',     'teal',   2,  array[]::text[]),
      ('INCOME',  'Side income',   'side-income',   'lime',   3,  array[]::text[]),
      ('INCOME',  'Bonus',         'bonus',         'amber',  4,  array[]::text[]),
      ('INCOME',  'Gift',          'gift',          'pink',   5,  array[]::text[]),
      ('INCOME',  'Refund',        'refund',        'sky',    6,  array[]::text[]),
      ('INCOME',  'Other',         'other',         'slate',  7,  array[]::text[]),
      ('INVESTMENT', 'SIP',         'sip',          'indigo', 1,  array[]::text[]),
      ('INVESTMENT', 'Mutual Fund', 'mutual-fund',  'violet', 2,  array[]::text[]),
      ('INVESTMENT', 'Stocks',      'stocks',       'green',  3,  array[]::text[]),
      ('INVESTMENT', 'PPF',         'ppf',          'blue',   4,  array[]::text[]),
      ('INVESTMENT', 'FD',          'fd',           'teal',   5,  array[]::text[]),
      ('INVESTMENT', 'Other',       'other',        'slate',  6,  array[]::text[])
    ) as v(type, name, icon, color, sort_order, subs)
  loop
    new_id := null;
    insert into public.categories (user_id, type, name, icon, color, sort_order, is_system)
    values (p_user_id, cat.type::public.transaction_type, cat.name, cat.icon, cat.color, cat.sort_order, true)
    on conflict do nothing
    returning id into new_id;

    if new_id is not null then
      i := 0;
      foreach sub in array cat.subs loop
        i := i + 1;
        insert into public.subcategories (user_id, category_id, name, sort_order)
        values (p_user_id, new_id, sub, i)
        on conflict do nothing;
      end loop;
    end if;
  end loop;
end;
$$;

-- Only the signup trigger may call this.
revoke execute on function public.seed_default_categories(uuid) from public, anon, authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, nullif(btrim(new.raw_user_meta_data ->> 'full_name'), ''))
  on conflict (id) do nothing;

  perform public.seed_default_categories(new.id);
  return new;
end;
$$;

revoke execute on function public.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Backfill any users created before this migration.
do $$
declare u record;
begin
  for u in select id, raw_user_meta_data from auth.users loop
    insert into public.profiles (id, full_name)
    values (u.id, nullif(btrim(u.raw_user_meta_data ->> 'full_name'), ''))
    on conflict (id) do nothing;
    if not exists (select 1 from public.categories where user_id = u.id) then
      perform public.seed_default_categories(u.id);
    end if;
  end loop;
end $$;

insert into app_private.migrations (name) values ('0003_new_user_seed.sql') on conflict do nothing;

-- ════════════════════════════════════════ 0004_analytics.sql
-- MoneyFollows — aggregation & query functions (called via supabase.rpc)
-- All are SECURITY INVOKER: they run as the calling user, so RLS still applies.
-- The explicit `user_id = auth.uid()` filters let Postgres use the user_id indexes.

-- ─────────────────────────────────────────────── totals by type for a period
create or replace function public.period_summary(p_from date, p_to date)
returns table (type public.transaction_type, total numeric, count bigint)
language sql stable
set search_path = ''
as $$
  select t.type, coalesce(sum(t.amount), 0), count(*)
  from public.transactions t
  where t.user_id = (select auth.uid())
    and t.transaction_date between p_from and p_to
  group by t.type
$$;

-- ─────────────────────────────────────────────── totals per category
create or replace function public.category_totals(
  p_from date,
  p_to date,
  p_type public.transaction_type default 'EXPENSE',
  p_purchase_only boolean default false
)
returns table (category_id uuid, name text, icon text, color text, total numeric, count bigint)
language sql stable
set search_path = ''
as $$
  select c.id, c.name, c.icon, c.color, sum(t.amount), count(*)
  from public.transactions t
  join public.categories c on c.id = t.category_id
  where t.user_id = (select auth.uid())
    and t.type = p_type
    and t.transaction_date between p_from and p_to
    and (not p_purchase_only or t.is_purchase)
  group by c.id, c.name, c.icon, c.color
  order by sum(t.amount) desc
$$;

-- ─────────────────────────────────────────────── totals per subcategory
create or replace function public.subcategory_totals(p_category_id uuid, p_from date, p_to date)
returns table (subcategory_id uuid, name text, total numeric, count bigint)
language sql stable
set search_path = ''
as $$
  select s.id, coalesce(s.name, 'Uncategorised'), sum(t.amount), count(*)
  from public.transactions t
  left join public.subcategories s on s.id = t.subcategory_id
  where t.user_id = (select auth.uid())
    and t.category_id = p_category_id
    and t.transaction_date between p_from and p_to
  group by s.id, s.name
  order by sum(t.amount) desc
$$;

-- ─────────────────────────────────────────────── per-day totals (charts, calendar)
create or replace function public.daily_totals(
  p_from date,
  p_to date,
  p_type public.transaction_type default 'EXPENSE'
)
returns table (day date, total numeric, count bigint)
language sql stable
set search_path = ''
as $$
  select t.transaction_date, sum(t.amount), count(*)
  from public.transactions t
  where t.user_id = (select auth.uid())
    and t.type = p_type
    and t.transaction_date between p_from and p_to
  group by t.transaction_date
  order by t.transaction_date
$$;

-- ─────────────────────────────────────────────── per-month totals (trends, MoM)
create or replace function public.monthly_totals(p_from date, p_to date)
returns table (month date, income numeric, expense numeric, investment numeric)
language sql stable
set search_path = ''
as $$
  select
    date_trunc('month', t.transaction_date)::date,
    coalesce(sum(t.amount) filter (where t.type = 'INCOME'), 0),
    coalesce(sum(t.amount) filter (where t.type = 'EXPENSE'), 0),
    coalesce(sum(t.amount) filter (where t.type = 'INVESTMENT'), 0)
  from public.transactions t
  where t.user_id = (select auth.uid())
    and t.transaction_date between p_from and p_to
  group by 1
  order by 1
$$;

-- ─────────────────────────────────────────────── search + filter + totals in one call
-- Returns one page of rows; every row also carries totals for the WHOLE filtered set.
create or replace function public.find_transactions(
  p_query text default null,
  p_from date default null,
  p_to date default null,
  p_type public.transaction_type default null,
  p_category_id uuid default null,
  p_subcategory_id uuid default null,
  p_min numeric default null,
  p_max numeric default null,
  p_purchase_only boolean default false,
  p_limit integer default 30,
  p_offset integer default 0
)
returns table (
  id uuid,
  type public.transaction_type,
  amount numeric,
  transaction_date date,
  description text,
  notes text,
  is_purchase boolean,
  category_id uuid,
  category_name text,
  category_icon text,
  category_color text,
  subcategory_id uuid,
  subcategory_name text,
  created_at timestamptz,
  total_count bigint,
  total_expense numeric,
  total_income numeric,
  total_investment numeric
)
language sql stable
set search_path = ''
as $$
  with q as (
    select nullif(btrim(p_query), '') as term
  )
  select
    t.id, t.type, t.amount, t.transaction_date, t.description, t.notes, t.is_purchase,
    c.id, c.name, c.icon, c.color,
    s.id, s.name,
    t.created_at,
    count(*) over (),
    coalesce(sum(t.amount) filter (where t.type = 'EXPENSE') over (), 0),
    coalesce(sum(t.amount) filter (where t.type = 'INCOME') over (), 0),
    coalesce(sum(t.amount) filter (where t.type = 'INVESTMENT') over (), 0)
  from public.transactions t
  join public.categories c on c.id = t.category_id
  left join public.subcategories s on s.id = t.subcategory_id
  cross join q
  where t.user_id = (select auth.uid())
    and (p_from is null or t.transaction_date >= p_from)
    and (p_to is null or t.transaction_date <= p_to)
    and (p_type is null or t.type = p_type)
    and (p_category_id is null or t.category_id = p_category_id)
    and (p_subcategory_id is null or t.subcategory_id = p_subcategory_id)
    and (p_min is null or t.amount >= p_min)
    and (p_max is null or t.amount <= p_max)
    and (not p_purchase_only or t.is_purchase)
    and (
      q.term is null
      or t.description ilike '%' || q.term || '%'
      or t.notes ilike '%' || q.term || '%'
      or c.name ilike '%' || q.term || '%'
      or s.name ilike '%' || q.term || '%'
    )
  order by t.transaction_date desc, t.created_at desc
  limit least(greatest(p_limit, 1), 200)
  offset greatest(p_offset, 0)
$$;

-- ─────────────────────────────────────────────── recurring transactions
-- First occurrence strictly after p_after, anchored on p_start (so 31 Jan → 28 Feb → 31 Mar).
create or replace function public.recurrence_next(
  p_start date,
  p_after date,
  p_frequency public.recurrence_frequency
)
returns date
language plpgsql immutable
set search_path = ''
as $$
declare
  n integer;
  candidate date;
begin
  if p_after < p_start then
    return p_start;
  end if;

  if p_frequency = 'DAILY' then
    return p_after + 1;
  elsif p_frequency = 'WEEKLY' then
    return p_start + ((floor((p_after - p_start) / 7.0)::integer + 1) * 7);
  elsif p_frequency = 'MONTHLY' then
    n := (extract(year from age(p_after, p_start)) * 12 + extract(month from age(p_after, p_start)))::integer;
    candidate := (p_start + make_interval(months => n))::date;
    while candidate <= p_after loop
      n := n + 1;
      candidate := (p_start + make_interval(months => n))::date;
    end loop;
    return candidate;
  else
    n := extract(year from age(p_after, p_start))::integer;
    candidate := (p_start + make_interval(years => n))::date;
    while candidate <= p_after loop
      n := n + 1;
      candidate := (p_start + make_interval(years => n))::date;
    end loop;
    return candidate;
  end if;
end;
$$;

-- Creates every due transaction for the current user and advances next_run_date.
-- Idempotent and safe to call on every app open; concurrent calls skip locked rows.
create or replace function public.generate_recurring_transactions(p_today date default current_date)
returns integer
language plpgsql
set search_path = ''
as $$
declare
  r record;
  due date;
  created integer := 0;
  guard integer;
begin
  for r in
    select *
    from public.recurring_transactions rt
    where rt.user_id = (select auth.uid())
      and rt.active
      and rt.next_run_date <= p_today
    for update skip locked
  loop
    due := r.next_run_date;
    guard := 0;
    while due <= p_today and (r.end_date is null or due <= r.end_date) and guard < 400 loop
      insert into public.transactions
        (user_id, type, amount, category_id, subcategory_id, transaction_date, description, is_purchase, recurring_id, investment_id)
      values
        (r.user_id, r.type, r.amount, r.category_id, r.subcategory_id, due, r.description, r.is_purchase, r.id, r.investment_id);
      created := created + 1;
      guard := guard + 1;
      due := public.recurrence_next(r.start_date, due, r.frequency);
    end loop;

    update public.recurring_transactions
    set next_run_date = due,
        active = r.end_date is null or due <= r.end_date
    where id = r.id;
  end loop;

  return created;
end;
$$;

-- Only signed-in users may call these (functions are executable by PUBLIC by default).
do $$
declare f text;
begin
  foreach f in array array[
    'public.period_summary(date, date)',
    'public.category_totals(date, date, public.transaction_type, boolean)',
    'public.subcategory_totals(uuid, date, date)',
    'public.daily_totals(date, date, public.transaction_type)',
    'public.monthly_totals(date, date)',
    'public.find_transactions(text, date, date, public.transaction_type, uuid, uuid, numeric, numeric, boolean, integer, integer)',
    'public.generate_recurring_transactions(date)'
  ] loop
    execute format('revoke execute on function %s from public, anon', f);
    execute format('grant execute on function %s to authenticated', f);
  end loop;
end $$;

insert into app_private.migrations (name) values ('0004_analytics.sql') on conflict do nothing;

-- ════════════════════════════════════════ 0005_top_transactions.sql
-- Largest transactions in a period (monthly review, PDF report, purchases).
create or replace function public.top_transactions(
  p_from date,
  p_to date,
  p_type public.transaction_type default 'EXPENSE',
  p_purchase_only boolean default false,
  p_limit integer default 5
)
returns table (
  id uuid,
  type public.transaction_type,
  amount numeric,
  transaction_date date,
  description text,
  notes text,
  is_purchase boolean,
  category_id uuid,
  category_name text,
  category_icon text,
  category_color text,
  subcategory_id uuid,
  subcategory_name text,
  created_at timestamptz
)
language sql stable
set search_path = ''
as $$
  select t.id, t.type, t.amount, t.transaction_date, t.description, t.notes, t.is_purchase,
         c.id, c.name, c.icon, c.color, s.id, s.name, t.created_at
  from public.transactions t
  join public.categories c on c.id = t.category_id
  left join public.subcategories s on s.id = t.subcategory_id
  where t.user_id = (select auth.uid())
    and t.type = p_type
    and t.transaction_date between p_from and p_to
    and (not p_purchase_only or t.is_purchase)
  order by t.amount desc, t.transaction_date desc
  limit least(greatest(p_limit, 1), 50)
$$;

revoke execute on function public.top_transactions(date, date, public.transaction_type, boolean, integer) from public, anon;
grant execute on function public.top_transactions(date, date, public.transaction_type, boolean, integer) to authenticated;

insert into app_private.migrations (name) values ('0005_top_transactions.sql') on conflict do nothing;
