/**
 * Concatenates all migrations into database/supabase-setup.sql for pasting into
 * Supabase → SQL Editor (no DB password needed). Records them in
 * app_private.migrations so `npm run db:migrate` later knows they're applied.
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { migrationFiles, migrationsDir, root } from "./lib/db.mts";

const files = await migrationFiles();
const parts = [
  "-- MoneyFollows — full database setup. Paste into Supabase → SQL Editor → Run.",
  "-- Generated by `npm run db:bundle`. Safe to run once on a fresh project.",
  "",
  "create schema if not exists app_private;",
  "revoke all on schema app_private from public;",
  "create table if not exists app_private.migrations (name text primary key, applied_at timestamptz not null default now());",
  "",
];
for (const f of files) {
  parts.push(`-- ════════════════════════════════════════ ${f}`, await readFile(join(migrationsDir, f), "utf8"), `insert into app_private.migrations (name) values ('${f}') on conflict do nothing;`, "");
}
await writeFile(join(root, "database", "supabase-setup.sql"), parts.join("\n"));
console.log(`✓ database/supabase-setup.sql (${files.length} migrations)`);
